use crate::registry::*;

pub fn entries() -> Vec<EndpointEntry> {
    vec![
        // --- Cached summary endpoints ---
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/statistics/network",
            description: "Network statistics summary",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/statistics/network")))),
            expect_status: 200,
            risk_tier: RiskTier::Low,
            read_pattern: ReadPattern::Cached,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/statistics/tx-stats",
            description: "Transaction statistics summary",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/statistics/tx-stats")))),
            expect_status: 200,
            risk_tier: RiskTier::Low,
            read_pattern: ReadPattern::Cached,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/statistics/recent-blocks",
            description: "Recent blocks statistics",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/statistics/recent-blocks")))),
            expect_status: 200,
            risk_tier: RiskTier::Low,
            read_pattern: ReadPattern::Cached,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/statistics/asset-ecosystem",
            description: "Asset ecosystem statistics",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/statistics/asset-ecosystem")))),
            expect_status: 200,
            risk_tier: RiskTier::Low,
            read_pattern: ReadPattern::Cached,
        },
        // --- Chart endpoints (Aggregation) ---
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/transaction-count",
            description: "Transaction count chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/transaction-count")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/cell-count",
            description: "Cell count chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/cell-count")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/knowledge-size",
            description: "Knowledge size chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/knowledge-size")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/common-knowledge-composition",
            description: "Common knowledge composition chart",
            resolve: Box::new(|base, _p| {
                Some(get(&format!("{base}/charts/common-knowledge-composition")))
            }),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/capacity-turnover-ratio",
            description: "Capacity turnover ratio chart",
            resolve: Box::new(|base, _p| {
                Some(get(&format!("{base}/charts/capacity-turnover-ratio")))
            }),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/cell-size-distribution",
            description: "Cell size distribution chart",
            resolve: Box::new(|base, _p| {
                Some(get(&format!("{base}/charts/cell-size-distribution")))
            }),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/address-cohort-retention",
            description: "Address cohort retention chart",
            resolve: Box::new(|base, _p| {
                Some(get(&format!("{base}/charts/address-cohort-retention")))
            }),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/most-utilized-scripts",
            description: "Most utilized scripts chart",
            resolve: Box::new(|base, _p| {
                Some(get(&format!("{base}/charts/most-utilized-scripts")))
            }),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/most-utilized-assets",
            description: "Most utilized assets chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/most-utilized-assets")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Cached,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/block-time-distribution",
            description: "Block time distribution chart",
            resolve: Box::new(|base, _p| {
                Some(get(&format!("{base}/charts/block-time-distribution")))
            }),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/epoch-time-distribution",
            description: "Epoch time distribution chart",
            resolve: Box::new(|base, _p| {
                Some(get(&format!("{base}/charts/epoch-time-distribution")))
            }),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/epoch-time-length",
            description: "Epoch time length chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/epoch-time-length")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/average-block-time",
            description: "Average block time chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/average-block-time")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/hash-rate",
            description: "Hash rate chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/hash-rate")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/difficulty",
            description: "Difficulty chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/difficulty")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/uncle-rate",
            description: "Uncle rate chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/uncle-rate")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/miner-address-distribution",
            description: "Miner address distribution chart",
            resolve: Box::new(|base, _p| {
                Some(get(&format!("{base}/charts/miner-address-distribution")))
            }),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/total-supply",
            description: "Total supply chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/total-supply")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/nominal-apc",
            description: "Nominal APC chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/nominal-apc")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/secondary-issuance",
            description: "Secondary issuance chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/secondary-issuance")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/inflation-rate",
            description: "Inflation rate chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/inflation-rate")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/charts/hodl-wave",
            description: "HODL wave chart",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/charts/hodl-wave")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/stats/daily-activities",
            description: "Daily activities statistics",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/stats/daily-activities")))),
            expect_status: 200,
            risk_tier: RiskTier::Medium,
            read_pattern: ReadPattern::Aggregation,
        },
        EndpointEntry {
            module: "statistics",
            method: Method::Get,
            path_template: "/stats/activity-summary-24h",
            description: "Activity summary for last 24 hours",
            resolve: Box::new(|base, _p| Some(get(&format!("{base}/stats/activity-summary-24h")))),
            expect_status: 200,
            risk_tier: RiskTier::Low,
            read_pattern: ReadPattern::Cached,
        },
    ]
}
