[package]
name = "ckbadger"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ckbadger"
path = "src/main.rs"

[dependencies]
ckbadger-config = { path = "../config" }
ckbadger-indexer = { path = "../indexer" }
ckbadger-api = { path = "../api" }
ckbadger-ipc = { path = "../ipc" }
ckbadger-tui = { path = "../tui" }
ckbadger-store = { path = "../ckbadger-store" }
clap = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
