name = ".bit Income Cell"
description = ".bit income aggregation type script."
website = "https://d.id/id-protocol/bit"

[[mainnet]]
code_hash = "0xebafc1ebe95b88cac426f984ed5fce998089ecad0cd2f8b17755c9de4cb02162"
data_hash = "0xd55d4d4a00bc77ae60808851ab2a3ead7dc364336658f64bd5a16ec75f2b1f37"
hash_type = "type"
