name = "ccBTC Oracle Cell"
description = "Oracle price cell type script carrying ccBTC and CKB feeds."

[mainnet]
[[mainnet.versions]]
canonical_ref_hash = "0x92156e93acbad7b1ac26c6364efed9bdd5a4f866cecfdf6217e2ea4374f325f0"
version_hash = "0x0b4a6b4bc17e0ed1e3537770eed2cabdd8dd476493251b0d0fbe27b8e5b5c9b8"
canonical_hash_type = "type"
