name = "TypeBurnLock"
description = "Unlocks when a specific type script is burned (appears in inputs but not outputs)."

[mainnet]
[[mainnet.versions]]
canonical_ref_hash = "0xff78bae0abf17d7a404c0be0f9ad9c9185b3f88dcc60403453d5ba8e1f22f53a"
version_hash = "0xff78bae0abf17d7a404c0be0f9ad9c9185b3f88dcc60403453d5ba8e1f22f53a"
canonical_hash_type = "data1"

[testnet]
[[testnet.versions]]
canonical_ref_hash = "0xff78bae0abf17d7a404c0be0f9ad9c9185b3f88dcc60403453d5ba8e1f22f53a"
version_hash = "0xff78bae0abf17d7a404c0be0f9ad9c9185b3f88dcc60403453d5ba8e1f22f53a"
canonical_hash_type = "data1"
