name = "Wrapped ETH (ForceBridge from BSC)"
symbol = "ETH|bsc"
decimals = 18
standard = "sudt"
icon = "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=002"

[mainnet]
code_hash = "0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5"
hash_type = "type"
args = "0xd61ddc3184767d677be0d741883779aa9513293c4eaa4e0687b5b1caf845edfe"
