name = "YAFATA"
symbol = "YFT"
decimals = 8
standard = "sudt"
icon = "data:application/octet-stream;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAtCAYAAADsvzj/AAAABHNCSVQICAgIfAhkiAAAABl0RVh0U29mdHdhcmUAZ25vbWUtc2NyZWVuc2hvdO8Dvz4AAAAmdEVYdENyZWF0aW9uIFRpbWUAS2FtIDIwIEp1biAyMDI0IDE3OjAwOjEw3o/7VQAAAYRJREFUaIHt1z9LAnEcx/GPR08hB82GCmqyJ9BQUGF/tGZbCsM4UKgpqDFLSzQSjAxLbJCCqCGNiPCBJDaYdDp1TW7WEB5EIvo7qS/H97Xd8bu73/v+cqb+ocFPGID03xPoFg6hhkOo4RBqOIQaDqGGQ6jhEGo4hBrDhPSIbDRqtyOTvsDYxDjeVVVbH9wJQJIkbG5vAQCOIhEsOF2o1+s/th8YGUYsGsX87BwAQJK+z2dj3Hk6jUBwr6M5mUT/2RPxOEqlV+zuhwAAFosFj9kcJmccqFSrWohSqSAUDrfcV7vjWhG+tQ4iUSy53TD3mgEAPllG5upSi/hrwiHFlyJy9znIa15YrVY4pqZxfJLo5tw6IvSMNBzGYni4y8LWZ0MylYL6of4a4/WswrO8oi3Lfh+e8nk9h21KV8ibouD69gaLThf8G+tNx5yeJXXd++3S/fp9LhRQKpdRq9W6MR9hhvmOGCZE+DtCjWGuCIdQwyHUcAg1HEINh1DDIdRwCDWGCfkCLLVna0fWmSUAAAAASUVORK5CYII="
description = "The First Token "

[mainnet]
code_hash = "0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5"
hash_type = "type"
args = "0x277a03bdcc4807ac7617dfea460ff77de9078b06b0456918b6f402113c7ef776"
