apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckbadger.fullname" . }}-secret
  labels:
    {{- include "ckbadger.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "ckbadger.databaseUrl" . | quote }}
  REDIS_URL: {{ include "ckbadger.redisUrl" . | quote }}
