apiVersion: v1
kind: Service
metadata:
  name: {{ include "ckbadger.fullname" . }}-api
  labels:
    {{- include "ckbadger.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ckbadger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ckbadger.fullname" . }}-frontend
  labels:
    {{- include "ckbadger.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ckbadger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
