[package]
name = "ckbadger-dob-decoder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ckb-vm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
