[package]
name = "ckbadger-task-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ckbadger-task-tui"
path = "src/main.rs"

[dependencies]
ckbadger-common = { path = "../common" }

tokio = { workspace = true }
ckbadger-store = { path = "../ckbadger-store" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }

ratatui = "0.29"
crossterm = "0.28"
ratatui-image = "4.0"

[dev-dependencies]
tokio-test = { workspace = true }
